### PR TITLE
Add support for calculating average of arbitrary number of angles

### PR DESCRIPTION
**Pull request by cinderblock**
I came across a need for this function and thought it might have a nice home in your package. Cheers!

### CODE REVIEW

**Comment by infusion** [comment]
Nice! Thanks for the contribution :)

**Comment by cinderblock** [comment]
Glad you like! I just noticed your comment about providing tests and such. I just did the implementation in the main `angles.js` file so tests are lacking. I also did not include a minified version.

**Comment by infusion** [comment]
If you could add some tests, it would be nice. I will minify the file with the next release.

**Comment by infusion** [comment]
BTW, I've seen your MLX90363 repo. Is this sensor worthwhile? According to the DSP sketch, it only calculates the angles for you. Are there any other benefits of using that sensor?

**Comment by cinderblock** [comment]
I'll try to write some tests tonight.

What do you think the result should be when someone asks for the average of the angles `[0, Math.PI]`? `NaN`? Something else?

I like the sensor. The SPI interface is a little weird, which is why I wrote my library for AVRs. I'm not sure what you mean by "DSP sketch". The sensor reports either a single angle, two angles, or all 3 component axes at up to ~1kHz. Melexis has other sensors that are faster. Competitors make very similar sensors as well. If you'd like to discuss this more, we should move this discussion to that project. ;)

**Comment by infusion** [comment]
I tend to return `null` in such cases - `NaN` is also ok. But beware, JavaScript does some magic: `Math.atan2(0,0) == 0` for whatever reason and `Math.atan2(Math.sin(0)+Math.sin(Math.PI), Math.cos(0)+Math.cos(Math.PI)) == Math.PI` for whatever reason, so you have to explicitly catch that case.

Sorry that was a bit vague. With DSP sketch I meant the diagram of the signal processor on page 52. Okay, I come over ;)

**Comment by cinderblock** [comment]
I'll defer to your standard. As long as it is documented, should be good!

`Math.atan2(0,0)` should be `NaN` or `null` imho but whatever, that's the implementation they went with.

Look like `Math.atan2(Math.sin(0)+Math.sin(Math.PI), Math.cos(0)+Math.cos(Math.PI)) == Math.PI` is true because `Math.cos(0) == 1`, `Math.cos(Math.PI) == -1`, and `Math.sin(0) == 0` but `Math.sin(Math.PI) != 0` for some reason. It's apparently less than `Number.EPSILON` but greater than `0`! Ha!
```
> Math.sin(Math.PI)
1.2246467991473532e-16
> Number.EPSILON
2.220446049250313e-16
> Math.sin(Math.PI) < Number.EPSILON
true
```

Note the fix I'm suggesting would take care of this degenerate case.

My apologies for not getting back to you sooner. I've been swamped with work recently and need to focus on that until next weekend. Wheee!

**Pull request merged**
